[package]
name = "video_converter"
version = "0.1.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ffmpeg-next = "4.3.8"
itertools = "0.10.0"
lazy_static = "1.4.0"
regex = "1.4.2"
simple-error = "0.2.2"
structopt = "0.3"
